In [1]:
import pandas as pd

/Users/janfrick/Documents/repos/vllm_diagnose_prediction/venv/lib/python3.12/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [5]:
pd.read_parquet('/Users/janfrick/Downloads/code_stats.parquet').head()

  code       fpr  fnr  support_pred  support_true
0  I10  0.583333  NaN            24            14
1  C22  0.500000  NaN             4             2
2  M15  1.000000  NaN             3             0
3  D64  0.833333  NaN             6             7
4  N39  0.750000  NaN             4             6

In [2]:
pd.read_parquet('data/cooccurrence.parquet').head()

  code_a code_b  joint_count       lift  count_a  count_b
0    A02    N31            3  15.539722       23      544
1    A02    K52            5  10.514439       23     1340
2    A02    G25            4   9.269308       23     1216
3    A02    Z94            6   7.777009       23     2174
4    A02    E10            3   6.986453       23     1210

In [3]:
['asd', 'poksj'] or []

['asd', 'poksj']

In [8]:
[] or None

In [9]:
list([])

[]

In [10]:
list(None)

TypeError: 'NoneType' object is not iterable